"""Generate and update project README.md.

Template-based structure (tables, links) with an agent-written summary
paragraph inserted when available.
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from urika.core.experiment import list_experiments
from urika.core.progress import load_progress
from urika.core.workspace import load_project_config


def generate_readme(project_dir: Path, summary: str = "") -> str:
    """Generate README.md content for a project.

    Args:
        project_dir: Path to the project directory.
        summary: Agent-written summary paragraph (optional).

    Returns:
        The full README.md content as a string.
    """
    config = load_project_config(project_dir)
    experiments = list_experiments(project_dir)

    parts: list[str] = []

    # Header
    parts.append(f"# {config.name}\n")
    parts.append(f"> {config.question}\n")

    # Description
    parts.append("## Description\n")
    if config.description:
        parts.append(f"{config.description}\n")
    else:
        parts.append(f"Mode: {config.mode}\n")

    # Current Status (agent-written or default)
    parts.append("## Current Status\n")
    if summary:
        parts.append(f"{summary}\n")
    else:
        n_exp = len(experiments)
        n_completed = sum(
            1
            for e in experiments
            if load_progress(project_dir, e.experiment_id).get("status") == "completed"
        )
        if n_exp == 0:
            parts.append("No experiments run yet.\n")
        else:
            parts.append(f"{n_completed}/{n_exp} experiments completed.\n")

    # Experiments table
    if experiments:
        parts.append("## Experiments\n")
        parts.append("| Experiment | Status | Runs | Key Finding |")
        parts.append("|-----------|--------|------|-------------|")
        for exp in experiments:
            progress = load_progress(project_dir, exp.experiment_id)
            runs = progress.get("runs", [])
            status = progress.get("status", "pending")
            finding = _get_key_finding(runs)
            summary_link = (
                f"[{exp.experiment_id}]"
                f"(experiments/{exp.experiment_id}/labbook/summary.md)"
            )
            parts.append(f"| {summary_link} | {status} | {len(runs)} | {finding} |")
        parts.append("")

    # Methods table
    methods = _load_methods(project_dir)
    if methods:
        parts.append("## Methods\n")
        parts.append("| Method | Experiment | Metrics | Status |")
        parts.append("|--------|-----------|---------|--------|")
        for m in methods:
            metrics_str = _format_metrics(m.get("metrics", {}))
            parts.append(
                f"| {m['name']} | {m.get('experiment', '')} "
                f"| {metrics_str} | {m.get('status', '')} |"
            )
        parts.append("")

    # Criteria
    criteria = _load_criteria(project_dir)
    if criteria:
        parts.append("## Criteria\n")
        c = criteria.get("criteria", {})
        ctype = c.get("type", "unknown")
        parts.append(f"Type: {ctype} (v{criteria.get('version', '?')})\n")
        threshold = c.get("threshold", {})
        primary = threshold.get("primary", {})
        if primary:
            metric = primary.get("metric", "")
            target = primary.get("target", "")
            direction = primary.get("direction", "higher")
            # Check if met
            best_val = _get_best_metric(methods, metric, direction)
            met = ""
            if best_val is not None:
                if direction == "higher" and best_val >= target:
                    met = " ✓"
                elif direction == "lower" and best_val <= target:
                    met = " ✓"
            parts.append(
                f"Primary: {metric} {'>' if direction == 'higher' else '<'} {target}{met}\n"
            )

    # Footer
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    parts.append("---")
    parts.append(f"*Auto-generated by Urika. Last updated: {now}*\n")

    return "\n".join(parts)


def write_readme(project_dir: Path, summary: str = "") -> Path:
    """Generate and write README.md to the project directory."""
    content = generate_readme(project_dir, summary)
    readme_path = project_dir / "README.md"
    readme_path.write_text(content, encoding="utf-8")
    return readme_path


def _load_methods(project_dir: Path) -> list[dict[str, Any]]:
    """Load methods from methods.json."""
    path = project_dir / "methods.json"
    if not path.exists():
        return []
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return data.get("methods", [])
    except (json.JSONDecodeError, KeyError):
        return []


def _load_criteria(project_dir: Path) -> dict[str, Any] | None:
    """Load latest criteria version."""
    path = project_dir / "criteria.json"
    if not path.exists():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        versions = data.get("versions", [])
        return versions[-1] if versions else None
    except (json.JSONDecodeError, KeyError, IndexError):
        return None


def _format_metrics(metrics: dict[str, Any]) -> str:
    """Format metrics dict as a short string."""
    if not metrics:
        return ""
    # Show top 2 numeric metrics
    numeric = {
        k: v
        for k, v in metrics.items()
        if isinstance(v, (int, float)) and not isinstance(v, bool)
    }
    if not numeric:
        return ""
    sorted_keys = sorted(numeric.keys())[:2]
    parts = []
    for k in sorted_keys:
        v = numeric[k]
        if isinstance(v, float) and 0 < v < 1:
            parts.append(f"{k}: {v:.1%}")
        elif isinstance(v, float):
            parts.append(f"{k}: {v:.2f}")
        else:
            parts.append(f"{k}: {v}")
    return ", ".join(parts)


def _get_key_finding(runs: list[dict[str, Any]]) -> str:
    """Extract a short key finding from runs."""
    if not runs:
        return ""
    last = runs[-1]
    obs = last.get("observation", "")
    if obs:
        # First sentence
        first_sentence = obs.split(".")[0].strip()
        if len(first_sentence) > 80:
            return first_sentence[:77] + "…"
        return first_sentence
    return last.get("method", "")


def _get_best_metric(
    methods: list[dict[str, Any]], metric: str, direction: str
) -> float | None:
    """Get the best value for a metric across all methods."""
    values = []
    for m in methods:
        val = m.get("metrics", {}).get(metric)
        if isinstance(val, (int, float)):
            values.append(val)
    if not values:
        return None
    return max(values) if direction == "higher" else min(values)
